apiVersion: v1
kind: Service
metadata:
  name: {{ include "logto.fullname" . }}
  labels:
    {{- include "logto.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.api }}
      targetPort: api
      protocol: TCP
      name: api
    - port: {{ .Values.service.ports.admin }}
      targetPort: admin
      protocol: TCP
      name: admin
  selector:
    {{- include "logto.selectorLabels" . | nindent 4 }}
